---
title: "Lec9"
author: "HO Yin Shan"
date: "2023-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = F,
                      warning = F)
library(tidyverse)
library(ggfortify)
```


```{r}
mallsales <- read_csv("mall_sales.csv")
```


```{r}
g1 <- lm(Sales~ Income +Competitors, data = mallsales)

  summary(g1)
  
```


```{r}
# Residuals

predicted <- predict(g1, mallsales)
  
# same results from following two methods
  
  residuals <-  mallsales$Sales - predicted
  
  g1$residuals
  
```



```{r}
qt(0.025, 62)*68.03

g1$fitted.values[1]

# interval
g1$fitted.values[1]+qt(0.025, 62)*68.03
g1$fitted.values[1]-qt(0.025, 62)*68.03
```

## Exercise

```{r Q1}
subprime <- read.csv("subprime.csv")
ncol(subprime)
nrow(subprime)
dim(subprime)
str(subprime)
```


```{r Q2}
summary(subprime$APR)
```

```{r Q3}
hist(subprime$APR, 
     xlab = 'APR',
     main = "Histogram of APR")
     #breaks = 20)
```

```{r Q4}
subprime[15,]
```

```{r Q5}
plot(subprime)
```

```{r Q6}
# correlation matrix
cor(subprime)

#subprime %>% 
#  PerformanceAnalytics::chart.Correlation()
```

```{r Q7}
model <- lm(APR~FICO+ LTV, data = subprime)
summary(model)
```

### Q8
For a fixed level of LTV, a unit increase of FICO will bring 0.01857 decrease on APR.

```{r Q9}
borrower <- data.frame(FICO = 650, LTV = 0.9)
prediction <- predict(model, borrower)

qt(0.025, 369)*1.242

# lower bound
prediction + qt(0.025, 369)*1.242
# upper bound
prediction - qt(0.025, 369)*1.242

# 95% CI is [7.76, 12.65]

predict.lm(model, borrower, interval = "pred", level = 0.95)

```


```{r Q9}
```

## Q10
R^2 equals to  0.4619.


# plot

```{r}
autoplot(g1)+ 
  theme_bw()
```

```{r}
# residuals 
plot(mallsales$Income, g1$residuals) 
plot(mallsales$Competitors, g1$residuals)
```

```{r}
qqnorm(g1$residuals)
qqline(g1$residuals) # add a line to the normal quantile plot
```

