
### Priming
priming = read.csv("priming.csv",header=T)
attach(priming)

#1
f1 = lm(Mailings~Awareness)
summary(f1)

#2 
# Three ways of answering this question:
# Use the scatterplot to visually check confounding variables
summary(priming)
plot(Hours[Awareness=="NO"], 
     Mailings[Awareness=="NO"], 
     xlim=c(0,4.3),ylim=c(0,93))

points(Hours[Awareness=="YES"], 
       Mailings[Awareness=="YES"], 
       col="red")

# Use a regression to check if Awareness and Hours are associated
f2 = lm(Hours~Awareness)
summary(f2)
  # the R-square is 0.002242 with an F-test p-value 0.6. Awareness explains almost nothing of the variation in Hours.
  # Awareness and Hours are not associated

# Use the vif, this is equivalent to using the RSquare because VIF=1/(1-RSquare)
install.packages('car')
f4 = lm(Mailings~Awareness+Hours)
library(car) # this package contains the vif() function
vif(f4)
  # the vif is very close to 1, indicating no association between the two predictors Awareness and Hours.



#3
f3 = lm(Mailings~Hours+Awareness+Hours:Awareness)
summary(f3)
# the interaction is significant with p-value 0.0117
# both main effects should be kept in the model


#4
# When customers are already aware of the product, the effect of Hours on Mailings is larger.
# When customers are already aware of the product, the contact of sales representatives is more effective in selling the product.
# Priming can increase mailings generated by per hour of contact by 4.308, and this increase is significant with the p-value 0.0117


#5
plot(Hours[Awareness=="NO"], 
     Mailings[Awareness=="NO"], 
     xlim=c(0,4.3),ylim=c(0,93),
     xlab="Hours", ylab="Mailings")

points(Hours[Awareness=="YES"], 
       Mailings[Awareness=="YES"], 
       col="red")

abline(c(2.454, 13.821))
abline(2.454, 13.821, col = 'blue')
abline(c(2.454+1.707, 13.821+4.308),col="red")

detach(priming)


